version: "3"

services:
  rails:
    image: tamle:test
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 3000:80
    links:
      - db
      - redis

  db:
    image: postgres:9.6-alpine
    environment:
      # - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=google_crawler_development
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=backend
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:5.0.5-alpine
    ports:
      - 6379:6379


volumes:
  db-data:
